services:
  - docker
before_install:
  # docker start
  - docker-compose up -d
  - docker ps -a
script:
  - docker container exec -it php composer install
  - docker container exec -it php php artisan key:generate
  - docker container exec -it php php artisan test
after_success:
  - docker-compose stop

