language: php
php:
  - 7.4
services:
  - docker
before_install:
  # Set AWS information
  - aws configure set aws_access_key_id 
  - aws configure set aws_secret_access_key 
  - aws configure set default.region ua
  - aws configure set metadata_service_timeout 1200
  - aws configure set metadata_service_num_attempts 3
  - aws configure list
  # docker start
  - docker-compose up -d
  - docker ps -a
script:
  - docker-compose exec php artisan test
after_success:
  - docker-compose stop

