version: '3'
services:
  alpha:
    image: nginx:latest
    container_name: "alpha"
    ports:
      - "0.0.0.0:${PORT}:80"
    volumes:
      - ./code/laraapp:/code
      - ./nginx/alpha/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/alpha/conf/common.conf:/etc/nginx/common.conf
      - ./nginx/alpha/conf/default.template:/etc/nginx/conf.d/default.template
      - ./nginx/alpha/log/access.log:/var/log/nginx/access.log
      - ./nginx/alpha/log/error.log:/var/log/nginx/error.log
    environment:
      MAIN_HOST: ${MAIN_HOST}
      ADMIN_HOST: ${ADMIN_HOST}
      SHOP_HOST: ${SHOP_HOST}
      SHOP_WWW_HOST: ${SHOP_WWW_HOST}
      LANDING_HOST: ${LANDING_HOST}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - web
      - redis

  web:
    image: nginx:latest
    container_name: "web"
    ports:
      - "8090:80"
    volumes:
      - ./code/laraapp:/code
      - ./nginx/web/conf/common.conf:/etc/nginx/common.conf
      - ./nginx/web/conf/common-php.conf:/etc/nginx/common-php.conf
      - ./nginx/web/conf/default.template:/etc/nginx/conf.d/default.template
      - ./nginx/web/log/access.log:/var/log/nginx/access.log
      - ./nginx/web/log/error.log:/var/log/nginx/error.log
    environment:
      MAIN_HOST: ${MAIN_HOST}
      ADMIN_HOST: ${ADMIN_HOST}
      SHOP_HOST: ${SHOP_HOST}
      SHOP_WWW_HOST: ${SHOP_WWW_HOST}
      LANDING_HOST: ${LANDING_HOST}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - php
  php:
    build: ./images/php-fpm/
    image: my-php-fpm
    container_name: "php"
    volumes:
      - ./code/laraapp:/code
      - ./php/default/conf.d:/usr/local/etc/php/conf.d
      - ./php/web/php-fpm.conf:/usr/local/etc/php-fpm.conf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    links:
      - db-master
      - db-slave
      - redis

  db-master:
    image: mariadb
    container_name: "db-master"
    ports:
      - "6603:3306"
    volumes:
      - ./mysql/dumps/dump.sql:/dumps/dump.sql
      - ./mysql/configs/db-master/mysql:/etc/mysql
      - ./mysql/logs/db-master/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db-slave:
    image: mariadb
    container_name: "db-slave"
    ports:
      - "6604:3306"
    volumes:
      - ./mysql/configs/db-slave/mysql:/etc/mysql
      - ./mysql/logs/db-slave/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:latest
    container_name: "redis"
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"

  shop:
    image: prestashop/prestashop:latest
    container_name: "shop"
    ports:
      - "8094:80"
    volumes:
      - ./code/myshop:/var/www/html
    environment:
      DB_SERVER: db-master
      DB_PREFIX: ${SHOP_DB_PREFIX}
      DB_NAME: ${SHOP_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_DOMAIN: ${SHOP_HOST}
      PS_FOLDER_ADMIN: admin421875
      ADMIN_MAIL: ${SHOP_ADMIN_MAIL}
      ADMIN_PASSWD: ${SHOP_ADMIN_PASSWORD}
    links:
      - db-master
