#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR/..
command="${@:1}"
echo "$DIR"
echo $command
docker-compose exec php bash -c "cd /code && curl -sS https://getcomposer.org/installer | php && php composer.phar $command"